# Generated by Django 5.1.2 on 2024-10-23 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0003_alter_principal_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='principal',
            old_name='Categoria',
            new_name='categoria',
        ),
    ]
