# Generated by Django 5.1.2 on 2024-10-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0004_rename_categoria_principal_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='principal',
            name='descuento',
            field=models.IntegerField(default=0),
        ),
    ]
